# Generated by Django 4.2.10 on 2024-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_residence_alter_report_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Residence',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
