# Generated by Django 4.2.10 on 2024-04-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_residence_remove_report_admin_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Residence',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
