# Generated by Django 4.2.10 on 2024-04-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_delete_residence_report_admin_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(max_length=200)),
                ('residence', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
            ],
        ),
    ]
