# Generated by Django 4.2.10 on 2024-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_delete_document_alter_report_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
