# Generated by Django 4.2.10 on 2024-04-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_report_type_userresidence_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
